openapi: 3.0.3
info:
  title: ${{ values.name }} API
  description: ${{ values.description if values.description else values.name + " Web API" }}
  version: 1.0.0
servers:
  - url: http://localhost:5000
    description: Local development
paths:
  /weatherforecast:
    get:
      summary: Get a 5-day weather forecast
      operationId: getWeatherForecast
      responses:
        "200":
          description: A list of weather forecasts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/WeatherForecast"
components:
  schemas:
    WeatherForecast:
      type: object
      properties:
        date:
          type: string
          format: date
        temperatureC:
          type: integer
          format: int32
        temperatureF:
          type: integer
          format: int32
        summary:
          type: string
      required:
        - date
        - temperatureC
        - temperatureF
